export type ToolId = "atlas" | "sunburst" | "dossier" | "compare" | "investigate" | "learn"

export type ToolDef = {
  id: ToolId
  name: string
  tag: string
  blurb: string
  learns: string[]
  href: string
  keywords: string[]
  phrases: string[]
  examples: string[]
}

export const tools: ToolDef[] = [
  {
    id: "atlas",
    name: "Typology Atlas",
    tag: "map",
    blurb: "World map of structural features: word order, tone, case, adpositions, inventories.",
    learns: [
      "Where a feature sits on Earth — belts, pockets, and gaps",
      "Which values cluster (SOV across Eurasia, VOS in Mesoamerica)",
      "What is simply uncoded, so you do not over-read grey dots",
    ],
    href: "/atlas?f=wals:81A",
    keywords: [
      "map",
      "atlas",
      "geography",
      "world",
      "sov",
      "svo",
      "vos",
      "word order",
      "tone",
      "case",
      "gender",
      "adposition",
      "preposition",
      "postposition",
      "consonant",
      "feature",
      "wals",
      "where",
      "distribution",
    ],
    phrases: ["where are", "on the map", "geographically", "word order map", "feature map"],
    examples: ["Where are SOV languages?", "Map tone systems", "Show case on the world map"],
  },
  {
    id: "sunburst",
    name: "WALS Sunburst Explorer",
    tag: "rings",
    blurb: "Glottolog genealogy as a radial sunburst, WALS features as outer rings, linked to a world map.",
    learns: [
      "Whether a value (like SOV) sits in one family — inheritance — or in one region across families — contact",
      "How a clade is distributed on Earth when you click its wedge",
      "What the map view implies for the tree when you filter genealogy by geography",
    ],
    href: "/sunburst?fam=indo1319&f=wals:81A",
    keywords: [
      "sunburst",
      "radial",
      "rings",
      "genealogy",
      "inheritance",
      "inherited",
      "contact",
      "areal",
      "clade",
      "indo-european",
      "germanic",
      "romance",
      "slavic",
      "feature rings",
      "linked map",
    ],
    phrases: [
      "sunburst",
      "feature rings",
      "inherited or",
      "family or contact",
      "genealogy and geography",
      "spread by family",
    ],
    examples: ["Did SOV spread by family or contact?", "Sunburst of Indo-European", "Filter the tree by the map"],
  },
  {
    id: "dossier",
    name: "Language Dossier",
    tag: "profile",
    blurb: "One language: family, coded features, Glottolog tree, structural and areal neighbors.",
    learns: [
      "The family tree and how sparse WALS vs Grambank is for that language",
      "Which languages are structurally nearest — relatives and not",
      "Who lives next door without sharing a family",
    ],
    href: "/language/kich1262",
    keywords: [
      "language",
      "profile",
      "dossier",
      "family",
      "tree",
      "nearest",
      "similar",
      "kiche",
      "k'iche'",
      "quiche",
      "mayan",
      "glottocode",
      "lookup",
    ],
    phrases: ["tell me about", "family tree", "closest languages", "profile of"],
    examples: ["Open K'iche'", "Family tree for a Mayan language", "Nearest languages to Hawaiian"],
  },
  {
    id: "compare",
    name: "Comparator",
    tag: "diff",
    blurb: "Feature-by-feature agreement table for two languages (WALS and Grambank).",
    learns: [
      "Exactly which coded features match or differ",
      "How much overlap the percentage is built from",
      "Whether two neighbors are copies or coincidences",
    ],
    href: "/compare",
    keywords: ["compare", "versus", "vs", "difference", "same", "agreement", "two", "pair", "contrast"],
    phrases: ["compare", " vs ", "versus", "difference between"],
    examples: ["Compare K'iche' and Kaqchikel", "Hindi vs Japanese"],
  },
  {
    id: "investigate",
    name: "Investigate",
    tag: "lab",
    blurb: "Guided questions: SOV geography, postpositions, Sprachbund, genealogy vs typology.",
    learns: [
      "Why SOV looks common: geography plus large families",
      "Which features travel with postpositions (harmonic order)",
      "How contact (Sprachbund) and genealogy each explain similarity",
    ],
    href: "/investigate/sov",
    keywords: [
      "why",
      "correlate",
      "correlation",
      "sprachbund",
      "areal",
      "contact",
      "neighbors",
      "genealogy",
      "family",
      "postposition",
      "harmonic",
      "investigate",
      "research",
      "question",
    ],
    phrases: ["why are", "how similar", "how much does", "unrelated neighbors", "postpositions"],
    examples: ["Why are SOV languages common?", "What correlates with postpositions?", "Balkan Sprachbund"],
  },
  {
    id: "learn",
    name: "Learn",
    tag: "primer",
    blurb: "Glossary, starter path, and what similarity percentages actually mean.",
    learns: [
      "The words: morphology, syntax, typology, Sprachbund",
      "A first path: library → K'iche' → map → Mesoamerica tour",
      "Why a 89% score is only as fair as the overlapping features",
    ],
    href: "/learn",
    keywords: [
      "learn",
      "glossary",
      "morphology",
      "syntax",
      "phonology",
      "typology",
      "what is",
      "define",
      "meaning",
      "cite",
      "citation",
      "beginner",
      "sprachbund",
      "areal",
    ],
    phrases: ["what is", "define", "how do i start", "glossary"],
    examples: ["What is a Sprachbund?", "How do I start?", "What do the percentages mean?"],
  },
]

export const investigateIntents: { id: string; href: string; keywords: string[] }[] = [
  { id: "sov", href: "/investigate/sov", keywords: ["sov", "word order", "geographically common", "eurasia"] },
  {
    id: "postpositions",
    href: "/investigate/postpositions",
    keywords: ["postposition", "preposition", "adposition", "harmonic", "correlate"],
  },
  {
    id: "neighbors",
    href: "/investigate/neighbors",
    keywords: ["sprachbund", "areal", "unrelated", "neighbors", "balkan", "mesoamerica", "contact"],
  },
  {
    id: "genealogy",
    href: "/investigate/genealogy",
    keywords: ["genealogy", "family", "inheritance", "related languages", "how much"],
  },
]
